image:
  name: docker/compose:1.24.0
  entrypoint: ["/bin/sh", "-c"]

services:
  - docker:dind

stages:
  - build
  - test
  - cover
  - release

variables:
  DOCKER_HOST: tcp://docker:2375/
  #DOCKER_HOST: tcp://localhost:2375
  DOCKER_DRIVER: overlay2
  VERSION: $CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA

before_script:
  - docker version
  - docker-compose version
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    - ./scripts/docker-build-push-test-img.sh

py-test:
  stage: test
  script:
    - docker pull $CI_REGISTRY_IMAGE:build-$VERSION
    - IMAGE=$CI_REGISTRY_IMAGE:build-$VERSION docker-compose -f docker-compose.yml run test
  artifacts:
    paths:
    - coverage/

lint:
  stage: test
  script:
    - docker pull $CI_REGISTRY_IMAGE:build-$VERSION
    - IMAGE=$CI_REGISTRY_IMAGE:build-$VERSION docker-compose -f docker-compose.yml run lint

cover:
  stage: cover
  script:
    - docker pull $CI_REGISTRY_IMAGE:build-$VERSION
    - IMAGE=$CI_REGISTRY_IMAGE:build-$VERSION docker-compose -f docker-compose.yml run cover
  dependencies:
    - py-test
  coverage: '/TOTAL.*\s(\d+)%/'

release-image:
  stage: release
  script:
    - ./scripts/docker-build-push-prod-img.sh
  #only:
  #  - master
