image:
  name: docker/compose:1.24.0
  entrypoint: ["/bin/sh", "-c"]

services:
  - docker:dind

stages:
  - build
  - test
  - cover
  - release

variables:
  DOCKER_HOST: tcp://docker:2375/
  #DOCKER_HOST: tcp://localhost:2375
  DOCKER_DRIVER: overlay2
  VERSION: $CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
  IMAGE: $CI_REGISTRY_IMAGE:build-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
  DCR: "docker-compose -f docker-compose.yml run"
  CODECOV_TOKEN: 2e46b3f9-08aa-41ac-88b7-bec1c93c8470

before_script:
  - docker version
  - docker-compose version
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    - ./scripts/docker-build-push-test-img.sh

.py_test: &py_test
  stage: test
  before_script:
    - export pytestParams="-v --capture=no --cov=hello_world --cov-report="
    - docker pull $IMAGE
  artifacts:
    paths:
      - coverage/

py-test-unit:
  <<: *py_test
  variables:
    COVERAGE_FILE: coverage/.coverage.unit
  script:
    - $DCR -e COVERAGE_FILE test pipenv run pytest $pytestParams --junitxml=coverage/junit-unit.xml tests/unit

py-test-func:
  <<: *py_test
  variables:
    COVERAGE_FILE: coverage/.coverage.func
  script:
    - $DCR -e COVERAGE_FILE test pipenv run pytest $pytestParams --junitxml=coverage/junit-func.xml tests/func

lint:
  stage: test
  script:
    - docker pull $IMAGE
    - $DCR lint

cover:
  stage: cover
  variables:
    COVERAGE_FILE: coverage/.coverage
  script:
    - docker pull $IMAGE
    - $DCR -e COVERAGE_FILE cover pipenv run coverage combine coverage/
    - $DCR -e COVERAGE_FILE cover
    - $DCR -e COVERAGE_FILE cover pipenv run coverage xml -o coverage/coverage.xml
    # We can't use the bash uploader because the docker/compose:1.24.0 image doesn't have bash !
    - $DCR -e CODECOV_TOKEN cover pipenv run codecov --file coverage/coverage.xml --disable=detect -F python --commit=$CI_COMMIT_SHA --branch=$CI_COMMIT_REF_SLUG
  artifacts:
    paths:
      - coverage/
    reports:
      junit: coverage/*.xml
  coverage: '/TOTAL.*\s(\d+)%/'

release-image:
  stage: release
  script:
    - ./scripts/docker-build-push-prod-img.sh
  dependencies: [] # We don't care about coverage/ reports
  #only:
  #  - master
