version: "3.7"
services:
  web:
    build:
      context: .
      target: run
      #args:
      #  - VERSION=${VERSION:-unknown}
    volumes:
      - .:/app
      - pipenv-venv:/root/.local/share/virtualenvs
  test:
    build:
      context: .
      target: test
    command: pipenv run pytest --verbose --capture=no
    volumes:
      - .:/app
      - pipenv-venv:/root/.local/share/virtualenvs

  lint:
    build:
      context: .
      target: test
    command: pipenv run flake8 app.py tests/ hello_world/
    volumes:
      - .:/app
      - pipenv-venv:/root/.local/share/virtualenvs

volumes:
  pipenv-venv: # Persist Pipenv venv (by default in ~/.local/share/virtualenvs)
