version: "3.7"
services:
  web:
    image: ${IMAGE:-gitlab-playground-run:latest}
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://myuser:mypass@db/myuser?sslmode=disable
      - FLASK_ENV=development

  test:
    image: ${IMAGE:-gitlab-playground-build:latest}
    command: pipenv run pytest --verbose --capture=no
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://myuser:mypass@db/myuser?sslmode=disable
      - DEBUG=True
      - TESTING=True
      - VERSION=unknown

  lint:
    image: ${IMAGE:-gitlab-playground-build:latest}
    command: pipenv run flake8 tests/ hello_world/

  db:
    image: postgres:11
    command: -c fsync=off -c synchronous_commit=off -c full_page_writes=off
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
