version: "3.7"
services:
  web:
    build:
      context: .
      target: run
    command: "--http-socket 0.0.0.0:5000 --processes 2 --module hello_world.app:app --py-autoreload 1"
    volumes:
      - .:/app
      - pipenv-venv:/root/.local/share/virtualenvs

  test:
    build:
      context: .
      target: build
    environment:
      - COVERAGE_FILE=coverage/.coverage
    volumes:
      - .:/app
      - pipenv-venv:/root/.local/share/virtualenvs

  lint:
    build:
      context: .
      target: build
    volumes:
      - .:/app
      - pipenv-venv:/root/.local/share/virtualenvs

  cover:
    build:
      context: .
      target: build
    environment:
      - COVERAGE_FILE=coverage/.coverage
    volumes:
      - .:/app
      - pipenv-venv:/root/.local/share/virtualenvs

volumes:
  pipenv-venv: # Persist Pipenv venv (by default in ~/.local/share/virtualenvs)
